# Generated by Django 5.1.1 on 2024-10-21 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocurrence',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Paciente envolvido na ocorrência', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_events', to='events.eventpatient'),
        ),
    ]
