# Generated by Django 5.1.1 on 2024-10-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventocurrence_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpatient',
            name='attendance',
            field=models.IntegerField(help_text='Número do Atendimento'),
        ),
        migrations.AlterField(
            model_name='eventpatient',
            name='record',
            field=models.IntegerField(help_text='Número do prontuário.'),
        ),
    ]
