# Generated by Django 5.1.2 on 2024-11-03 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0002_alter_damageclassification_options_and_more'),
        ('events', '0003_alter_eventpatient_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(help_text='Nome da Meta', max_length=255)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseOcurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Descrição da tratativa')),
                ('send_manager', models.BooleanField(default=False, help_text='Enviado para o gestor ?')),
                ('event_investigation', models.BooleanField(default=False, help_text='Investigação do Evento ?')),
            ],
            options={
                'verbose_name': 'Tratativa',
                'verbose_name_plural': 'Tratativas',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='eventocurrence',
            name='events_even_inciden_b02e4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventocurrence',
            name='events_even_ocurren_034e96_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventocurrence',
            name='events_even_damage__535a6b_idx',
        ),
        migrations.RemoveField(
            model_name='eventocurrence',
            name='damage_classification',
        ),
        migrations.RemoveField(
            model_name='eventocurrence',
            name='incident_classification',
        ),
        migrations.RemoveField(
            model_name='eventocurrence',
            name='ocurrence_classification',
        ),
        migrations.AddField(
            model_name='metas',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='damage_classification',
            field=models.ForeignKey(help_text='Classificação do Dano', on_delete=django.db.models.deletion.DO_NOTHING, related_name='damage_response_ocurrence', to='classifications.damageclassification'),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='incident_classification',
            field=models.ForeignKey(help_text='Classificação do Incidente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='incident_response_ocurrence', to='classifications.incidentclassification'),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='meta',
            field=models.OneToOneField(help_text='Meta', on_delete=django.db.models.deletion.PROTECT, related_name='meta_response_ocurrence', to='events.metas'),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='ocurrence',
            field=models.OneToOneField(help_text='Ocorrencia relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='response_ocurrence', to='events.eventocurrence'),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='ocurrence_classification',
            field=models.ForeignKey(help_text='Classificação da Ocorrência', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ocurrence_response_ocurrence', to='classifications.ocurrenceclassification'),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='metas',
            index=models.Index(fields=['name'], name='events_meta_name_a4f893_idx'),
        ),
        migrations.AddIndex(
            model_name='responseocurrence',
            index=models.Index(fields=['ocurrence'], name='events_resp_ocurren_14e98c_idx'),
        ),
        migrations.AddIndex(
            model_name='responseocurrence',
            index=models.Index(fields=['send_manager'], name='events_resp_send_ma_ebae00_idx'),
        ),
        migrations.AddIndex(
            model_name='responseocurrence',
            index=models.Index(fields=['event_investigation'], name='events_resp_event_i_8d4cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='responseocurrence',
            index=models.Index(fields=['incident_classification'], name='events_resp_inciden_fe7243_idx'),
        ),
        migrations.AddIndex(
            model_name='responseocurrence',
            index=models.Index(fields=['ocurrence_classification'], name='events_resp_ocurren_9e9a34_idx'),
        ),
        migrations.AddIndex(
            model_name='responseocurrence',
            index=models.Index(fields=['damage_classification'], name='events_resp_damage__cce7d3_idx'),
        ),
    ]
