# Generated by Django 5.1.2 on 2024-11-03 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_metas_responseocurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcurrenceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Descrição da Ocorrência')),
            ],
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='deadline_response',
            field=models.DateField(blank=True, help_text='Prazo da Resposta', null=True),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Resolvido ?'),
        ),
        migrations.AddField(
            model_name='responseocurrence',
            name='ocurrence_description',
            field=models.ForeignKey(default=1, help_text='Descrição da Ocorrência', on_delete=django.db.models.deletion.PROTECT, to='events.ocurrencedescription'),
            preserve_default=False,
        ),
    ]
