# Generated by Django 5.1.2 on 2024-11-03 02:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_ocurrencedescription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocurrencedescription',
            options={'ordering': ['created_at'], 'verbose_name': 'Descrição da Ocorrência', 'verbose_name_plural': 'Descrições das Ocorrências'},
        ),
        migrations.AddField(
            model_name='ocurrencedescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocurrencedescription',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocurrencedescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ocurrencedescription',
            name='name',
            field=models.TextField(help_text='Descrição da Ocorrência', max_length=255),
        ),
        migrations.AddIndex(
            model_name='ocurrencedescription',
            index=models.Index(fields=['name'], name='events_ocur_name_8123b8_idx'),
        ),
    ]
