# Generated by Django 5.1.1 on 2024-11-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_genere_eventpatient_genere_race_eventpatient_race_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genere',
            new_name='Gender',
        ),
        migrations.RenameIndex(
            model_name='gender',
            new_name='events_gend_name_3a83e2_idx',
            old_name='events_gene_name_e7ceae_idx',
        ),
    ]
