# Generated by Django 5.1.2 on 2024-11-09 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_genere_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocurrence',
            name='immediate_action',
            field=models.TextField(help_text='O que foi realizado após a ocorrência / Ação imediata'),
        ),
        migrations.AlterField(
            model_name='responseocurrence',
            name='description',
            field=models.TextField(help_text='Realize a descrição da tratativa'),
        ),
        migrations.AlterField(
            model_name='responseocurrence',
            name='meta',
            field=models.OneToOneField(help_text='Meta Anvisa', on_delete=django.db.models.deletion.PROTECT, related_name='meta_response_ocurrence', to='events.metas'),
        ),
        migrations.AlterField(
            model_name='responseocurrence',
            name='ocurrence',
            field=models.OneToOneField(help_text='Informe a Ocorrência relacionada', on_delete=django.db.models.deletion.PROTECT, related_name='response_ocurrence', to='events.eventocurrence'),
        ),
        migrations.AlterField(
            model_name='responseocurrence',
            name='ocurrence_description',
            field=models.ForeignKey(help_text='Selecione a descrição da ocorrência', on_delete=django.db.models.deletion.PROTECT, to='events.ocurrencedescription'),
        ),
    ]
