# Generated by Django 5.1.2 on 2024-11-10 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_eventocurrence_immediate_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseocurrence',
            name='meta',
            field=models.ForeignKey(help_text='Meta Anvisa', on_delete=django.db.models.deletion.PROTECT, related_name='meta_response_ocurrence', to='events.metas'),
        ),
    ]
