site_name: SafeCare Documentation
repo_url: https://github.com/matheuskdev/notificacao_hospitalar.git
repo_name: matheuskdev/notificacao_hospitalar
edit_uri: docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
          
extra_css: []
extra_javascript: []
