from django.core.management.base import BaseCommand
from events.models.response_ocurrence_models import OcurrenceDescription

class Command(BaseCommand):
    help = 'Populates the OcurrenceDescription table with predefined data'

    def handle(self, *args, **kwargs):
        data = [
            (0, "Não se Aplica"),
            (1, "Meta 1 - Identificação: Paciente - dispositivo - medicamento - nutrição - Prontuário"),
            (2, "Meta 2 - Falha na comunicação entre os profissionais"),
            (3, "Meta 3 - Farmacovigilância - Erro de Medicação"),
            (4, "Meta 4 - Falha na cirurgia - erro - cancelamento - reoperação 48h - óbito 7 dias, Não Sinalização de lateralidade"),
            (5, "Meta 5 - Falha na higienização das mãos"),
            (6, "Meta 6 - LPP - Lesão por pressão - ou por lesão por dispositivo médico"),
            (7, "Falha na assistência"),
            (8, "Tecnovigilância - Queixa técnica"),
            (9, "Falha do transporte"),
            (10, "Atraso no atendimento"),
            (11, "Falha no uso de EPI"),
            (12, "Falha na Prescrição"),
            (13, "Queda do paciente - meta 6"),
            (14, "Procedimento inadequado (Ajuste de Rotina)"),
            (15, "Prontuário Incompleto - falta de: protocolo - evolução - transferência - termo - sem registro de volume infundido"),
            (16, "Falha na dispensação"),
            (17, "Hemovigilância - Reação transfusional - Ficha incompleta"),
            (18, "Perda de dispositivo - SNG"),
            (19, "Dieta com alterações de deterioração, Defeito no conector"),
            (20, "Flebite"),
            (21, "Falha na dupla checagem do material"),
            (22, "Glosa pelo convênio"),
            (23, "Readmissões em até 48h após a alta na emergência/ Internação até 48h na UTI"),
            (24, "Extravasamento de contraste"),
            (25, "Evasão"),
            (26, "Óbito inesperado"),
            (27, "Saneantes"),
            (28, "IRAS - Infecção relacionada à assistência à saúde"),
            (29, "Desnutrição"),
            (30, "Diarreia"),
            (31, "Ergonomia"),
            (32, "Alta indevida"),
            (33, "Comportamental"),
            (34, "Paciente sem acompanhante"),
            (35, "Produto para ser substituído"),
            (36, "Quebra de acordo entre as partes (não conformidade)"),
            (37, "Reintubação 24h"),
            (38, "Médico sem cadastro no hospital - médico sem cadastro no sistema Medview"),
            (39, "Broncoaspiração"),
            (40, "PAV - Pneumonia associada à ventilação mecânica"),
            (41, "Perda de dispositivo - SNE"),
            (42, "Perda de dispositivo - TOT"),
            (43, "Perda de dispositivo - SVD"),
            (44, "Perda de dispositivo - AVP"),
            (45, "Perda de dispositivo - AVC"),
            (46, "Perda de dispositivo - PICC/PAI"),
            (47, "Perda de dispositivo - CTL"),
            (48, "Reoperação 48h"),
            (49, "Óbito 7 dias"),
            (50, "Reação alérgica ao fármaco"),
            (51, "Erro de infusão"),
            (52, "Cancelamento de cirurgia"),
            (53, "Paciente admitida no hospital com lesões por pressão"),
            (54, "Registro de volume infundido da dieta enteral incompleto"),
            (55, "Protocolo de dor torácica"),
            (56, "Falha na Higienização"),
            (57, "Prescrição manual"),
            (58, "Aprazamento"),
            (59, "Perda de dispositivo - GTT"),
            (60, "Óbito Gatilho"),
            (61, "Protocolo de TEV - RISCO DE TEV E USO DA PROFILAXIA EM PACIENTES CLÍNICOS INTERNADOS"),
            (62, "Protocolo de Sepse"),
            (63, "Tempo de administração de antibioticoprofilaxia cirúrgica"),
            (64, "Falha no tratamento de DOR"),
            (65, "ITU"),
            (66, "Administração de dieta enteral inadequada (Vencida, volume menor/maior do que o prescrito)"),
            (67, "Organizacional"),
            (68, "Cardápio"),
            (69, "Ausência ou falha de preenchimento do Termo para procedimento cirúrgico/Anestésico/hemocomponentes"),
            (70, "Infecção FO pelo Dispositivo médico"),
            (71, "Farmacovilância - Queixa técnica"),
            (72, "Fratura após assistência"),
            (73, "Desvio de qualidade"),
            (74, "Circunstância de Risco"),
            (75, "Falha na Comunicação"),
            (76, "Atraso na entrega do medicamento prescrito"),
            (77, "Transporte e transferência não preenchido/Transporte seguro"),
            (78, "Suspensão de Cirurgia"),
            (79, "Prontuário Eletrônico"),
            (80, "Atraso na entrega de dieta"),
            (81, "Problemas com Equipamento- Ar condicionado, termômetro"),
            (82, "Suporte de TI"),
            (83, "Retorno < 48h"),
            (84, "Jejum Prolongado"),
            (85, "Descarte inadequado de perfurocortantes"),
            (86, "Extravasamento/infiltração de medicação endovenosa"),
            (87, "Acidente de trabalho"),
            (88, "DO - Declaração de Óbito"),
            (89, "Material CME")
        ]

        for id_evento, descricao in data:
            OcurrenceDescription.objects.get_or_create(name=descricao)

        self.stdout.write(self.style.SUCCESS('Successfully populated OcurrenceDescription table.'))
