# Generated by Django 5.1.1 on 2024-11-29 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_text', models.TextField(help_text='Resposta do Gestor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('response_ocurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_responses', to='responses.responseocurrence')),
            ],
            options={
                'verbose_name': 'Resposta do Gestor',
                'verbose_name_plural': 'Respostas dos Gestores',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['response_ocurrence'], name='manager_res_respons_d6e59a_idx')],
            },
        ),
    ]
