# Generated by Django 5.1.1 on 2024-11-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classifications", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Metas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.TextField(help_text="Nome da Meta", max_length=255),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Metas",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OcurrenceDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.TextField(
                        help_text="Descrição da Ocorrência", max_length=255
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Descrição da Ocorrência",
                "verbose_name_plural": "Descrições das Ocorrências",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseOcurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Realize a descrição da tratativa"
                    ),
                ),
                (
                    "deadline_response",
                    models.DateField(
                        blank=True, help_text="Prazo da Resposta", null=True
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Resolvido ?"
                    ),
                ),
                (
                    "send_manager",
                    models.BooleanField(
                        default=False, help_text="Enviado para o gestor ?"
                    ),
                ),
                (
                    "event_investigation",
                    models.BooleanField(
                        default=False, help_text="Investigação do Evento ?"
                    ),
                ),
                (
                    "damage_classification",
                    models.ForeignKey(
                        help_text="Classificação do Dano",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="damage_response_ocurrence",
                        to="classifications.damageclassification",
                    ),
                ),
                (
                    "incident_classification",
                    models.ForeignKey(
                        help_text="Classificação do Incidente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="incident_response_ocurrence",
                        to="classifications.incidentclassification",
                    ),
                ),
                (
                    "meta",
                    models.ForeignKey(
                        help_text="Meta Anvisa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meta_response_ocurrence",
                        to="responses.metas",
                    ),
                ),
                (
                    "ocurrence",
                    models.OneToOneField(
                        help_text="Informe a Ocorrência relacionada",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="response_ocurrence",
                        to="events.eventocurrence",
                    ),
                ),
                (
                    "ocurrence_classification",
                    models.ForeignKey(
                        help_text="Classificação da Ocorrência",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ocurrence_response_ocurrence",
                        to="classifications.ocurrenceclassification",
                    ),
                ),
                (
                    "ocurrence_description",
                    models.ForeignKey(
                        help_text="Selecione a descrição da ocorrência",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="responses.ocurrencedescription",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tratativa",
                "verbose_name_plural": "Tratativas",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="metas",
            index=models.Index(
                fields=["name"], name="responses_m_name_848ab1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocurrencedescription",
            index=models.Index(
                fields=["name"], name="responses_o_name_bd0329_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="responseocurrence",
            index=models.Index(
                fields=["ocurrence"], name="responses_r_ocurren_689252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="responseocurrence",
            index=models.Index(
                fields=["send_manager"], name="responses_r_send_ma_51e4dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="responseocurrence",
            index=models.Index(
                fields=["event_investigation"],
                name="responses_r_event_i_4f1a9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseocurrence",
            index=models.Index(
                fields=["incident_classification"],
                name="responses_r_inciden_7f36ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseocurrence",
            index=models.Index(
                fields=["ocurrence_classification"],
                name="responses_r_ocurren_0a6307_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="responseocurrence",
            index=models.Index(
                fields=["damage_classification"],
                name="responses_r_damage__5c9662_idx",
            ),
        ),
    ]
