# Generated by Django 5.1.1 on 2024-10-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('classification', models.CharField(help_text='Tipo da classificação do dano.', max_length=255)),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['classification'],
                'indexes': [models.Index(fields=['classification'], name='classificat_classif_8aae50_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('classification', models.CharField(help_text='Tipo da classificação do incidente.', max_length=255)),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['classification'],
                'indexes': [models.Index(fields=['classification'], name='classificat_classif_f04a22_idx')],
            },
        ),
        migrations.CreateModel(
            name='OcurrenceClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('classification', models.CharField(help_text='Tipo da classificação da ocorrência.', max_length=255)),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['classification'],
                'indexes': [models.Index(fields=['classification'], name='classificat_classif_4f9ed4_idx')],
            },
        ),
    ]
