# Generated by Django 5.1.1 on 2024-11-13 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do departamento. Deve ser único.",
                        max_length=255,
                        unique=True,
                        validators=[utils.validators.validate_not_empty],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Descrição do departamento. Opcional.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name"], name="departments_name_33d25b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_department_name"
                    )
                ],
            },
        ),
    ]
