# Generated by Django 5.1.1 on 2024-10-30 11:11

from django.db import migrations, models

import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Nome do departamento. Deve ser único.', max_length=255, unique=True, validators=[utils.validators.validate_not_empty]),
        ),
    ]
